import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Linking from "expo-linking";
import { Alert, Pressable, StyleSheet, View } from "react-native";
import { router } from "expo-router";

import { AppText, IconButton, LabScreen, ScreenTitle, colors } from "@/components/lab-ui";

const whatsappUrl = "https://wa.me/967774824922";
const emailUrl = "mailto:badralmolaiky02@gmail.com?subject=%D8%AA%D9%88%D8%A7%D8%B5%D9%84%20%D8%A8%D8%AE%D8%B5%D9%88%D8%B5%20%D9%86%D8%B8%D8%A7%D9%85%20%D8%AD%D8%B3%D8%A7%D8%A8%D8%A7%D8%AA%20%D9%85%D8%AE%D8%AA%D8%A8%D8%B1%20%D8%A7%D9%84%D8%A3%D8%B3%D9%86%D8%A7%D9%86";
async function openContact(url: string) { try { await Linking.openURL(url); } catch { Alert.alert("تعذر فتح الرابط", "تأكد من توفر تطبيق واتساب أو تطبيق بريد إلكتروني على الجهاز."); } }
export default function ContactScreen() { return <LabScreen><View style={styles.header}><IconButton icon="close" onPress={() => router.back()} /><ScreenTitle title="تواصل معنا" subtitle="الدعم والاستفسارات الخاصة بالنظام" /></View><View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="support-agent" size={32} color="#fff" /></View><AppText style={styles.heroTitle}>نحن هنا لمساعدتك</AppText><AppText style={styles.heroText}>اختر وسيلة التواصل المناسبة لإرسال الملاحظات أو طلب المساعدة.</AppText></View><Pressable onPress={() => openContact(whatsappUrl)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={[styles.cardIcon, { backgroundColor: "#DCF8E7" }]}><MaterialIcons name="chat" size={24} color="#16803C" /></View><View style={styles.copy}><AppText style={styles.cardTitle}>التواصل عبر واتساب</AppText><AppText style={styles.cardSub}>00967774824922</AppText></View><MaterialIcons name="chevron-left" size={24} color={colors.muted} /></Pressable><Pressable onPress={() => openContact(emailUrl)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={[styles.cardIcon, { backgroundColor: colors.tealSoft }]}><MaterialIcons name="email" size={24} color={colors.primary} /></View><View style={styles.copy}><AppText style={styles.cardTitle}>البريد الإلكتروني</AppText><AppText style={styles.cardSub}>badralmolaiky02@gmail.com</AppText></View><MaterialIcons name="chevron-left" size={24} color={colors.muted} /></Pressable><View style={styles.note}><MaterialIcons name="info-outline" size={18} color={colors.primary} /><AppText style={styles.noteText}>تفتح الروابط بتطبيق واتساب أو تطبيق البريد الإلكتروني المتوفر على جهازك.</AppText></View></LabScreen>; }
const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", gap: 12, alignItems: "flex-start" }, hero: { backgroundColor: colors.primary, borderRadius: 24, padding: 20, alignItems: "center", gap: 7 }, heroIcon: { width: 62, height: 62, borderRadius: 21, backgroundColor: "#148679", alignItems: "center", justifyContent: "center", marginBottom: 2 }, heroTitle: { color: "#fff", fontFamily: "Cairo-Bold", fontSize: 18 }, heroText: { color: "#C9E9E3", textAlign: "center", fontSize: 11, lineHeight: 19 }, card: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 14, minHeight: 78, flexDirection: "row-reverse", alignItems: "center", gap: 12 }, cardIcon: { width: 46, height: 46, borderRadius: 15, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, alignItems: "flex-end" }, cardTitle: { fontFamily: "Cairo-Bold", fontSize: 13 }, cardSub: { color: colors.muted, fontSize: 10, marginTop: 3, writingDirection: "ltr" }, note: { flexDirection: "row-reverse", gap: 8, backgroundColor: colors.tealSoft, borderRadius: 14, padding: 12, alignItems: "flex-start" }, noteText: { flex: 1, color: colors.primary, fontSize: 10, lineHeight: 17, textAlign: "right" }, pressed: { opacity: 0.7 } });
