import { Alert, Modal, Pressable, StyleSheet, View } from "react-native";
import { useState } from "react";
import { router } from "expo-router";

import { CashboxField } from "@/components/cashbox-field";
import { DateField } from "@/components/date-field";
import { AppText, EmptyState, FormInput, IconButton, LabScreen, PrimaryButton, ScreenTitle, SelectField, SelectionSheet, colors } from "@/components/lab-ui";
import { formatMoney } from "@/lib/lab-format";
import { expenseReceiptHtml, sharePdf } from "@/lib/pdf-reports";
import { trpc } from "@/lib/trpc";

const today = new Date().toISOString().slice(0, 10);
const costTypes = [
  { value: "materials", label: "تكلفة المواد" }, { value: "wages", label: "رواتب العمال" }, { value: "rent", label: "الإيجارات" }, { value: "installments", label: "الأقساط" }, { value: "utilities", label: "الكهرباء والماء والمرافق" }, { value: "other", label: "نثريات وتكاليف أخرى" },
] as const;
type CostType = (typeof costTypes)[number]["value"];

export default function CostsScreen() {
  const { data: costs, isLoading } = trpc.lab.costs.list.useQuery();
  const { data: currencies = [] } = trpc.lab.currencies.list.useQuery();
  const { data: profile } = trpc.lab.profile.get.useQuery();
  const utils = trpc.useUtils();
  const [open, setOpen] = useState(false); const [typeSheet, setTypeSheet] = useState(false); const [currencySheet, setCurrencySheet] = useState(false);
  const [costType, setCostType] = useState<CostType>("materials"); const [category, setCategory] = useState(""); const [amount, setAmount] = useState(""); const [expenseDate, setExpenseDate] = useState(today); const [cashboxId, setCashboxId] = useState<number | null>(null); const [currencyCode, setCurrencyCode] = useState<"YER" | "SAR" | "USD">("YER"); const [notes, setNotes] = useState("");
  const create = trpc.lab.costs.create.useMutation({ onSuccess: async () => { await Promise.all([utils.lab.costs.invalidate(), utils.lab.reports.invalidate(), utils.lab.dashboard.invalidate(), utils.lab.cashboxes.invalidate()]); setOpen(false); setCategory(""); setAmount(""); setNotes(""); setCashboxId(null); setCostType("materials"); }, onError: (error) => Alert.alert("تعذر الحفظ", error.message) });
  const remove = trpc.lab.costs.delete.useMutation({ onSuccess: () => { utils.lab.costs.invalidate(); utils.lab.reports.invalidate(); utils.lab.dashboard.invalidate(); }, onError: (error) => Alert.alert("تعذر الحذف", error.message) });
  const selectedType = costTypes.find((entry) => entry.value === costType)?.label;
  const activeCurrencies = currencies.filter((entry) => entry.isActive);
  const selectedCurrency = activeCurrencies.find((entry) => entry.currencyCode === currencyCode);
  const printExpense = async (item: NonNullable<typeof costs>[number]) => { if (!profile) return; try { await sharePdf(expenseReceiptHtml(profile, { reference: item.id, expenseDate: item.expenseDate, category: item.category, costType: item.costType, amount: String(item.amount), currencyCode: item.currencyCode, notes: item.notes }), `سند مصروف ${item.id}`); } catch (error) { Alert.alert("تعذر الطباعة", error instanceof Error ? error.message : "تعذر تجهيز السند."); } };
  return <LabScreen><View style={styles.header}><IconButton icon="close" onPress={() => router.back()} /><ScreenTitle title="حساب التكاليف" subtitle="المواد والرواتب والإيجارات والأقساط والمرافق والنثريات" /></View><PrimaryButton label="إضافة تكلفة" onPress={() => setOpen(true)} icon="add" />
    {isLoading ? null : !costs?.length ? <EmptyState title="لا توجد تكاليف مسجلة" description="أدخل مصروفات المختبر لتظهر في تقرير الأرباح والخسائر." icon="receipt-long" /> : <View style={styles.list}>{costs.map((item) => <View key={item.id} style={styles.card}><Pressable onPress={() => Alert.alert("حذف تكلفة", "هل تريد حذف هذا القيد؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => remove.mutate({ id: item.id }) }])} style={({ pressed }) => [styles.delete, pressed && styles.pressed]}><AppText style={styles.deleteText}>حذف</AppText></Pressable><View style={styles.copy}><AppText style={styles.name}>{item.category}</AppText><AppText style={styles.meta}>{costTypes.find((entry) => entry.value === item.costType)?.label ?? item.costType} · {item.expenseDate}</AppText>{item.notes ? <AppText style={styles.notes}>{item.notes}</AppText> : null}</View><View style={styles.amountBlock}><AppText style={styles.amount}>{formatMoney(item.amount)} {item.currencyCode}</AppText><Pressable onPress={() => printExpense(item)}><AppText style={styles.printText}>طباعة PDF</AppText></Pressable></View></View>)}</View>}
    <Modal visible={open} transparent animationType="fade"><View style={styles.backdrop}><View style={styles.modal}><AppText style={styles.title}>قيد تكلفة جديد</AppText><SelectField label="نوع التكلفة" value={selectedType} placeholder="اختر النوع" onPress={() => setTypeSheet(true)} /><FormInput label="البند أو الوصف" value={category} onChangeText={setCategory} placeholder="مثال: جبس أو فاتورة كهرباء" /><View style={styles.twoCols}><View style={styles.flex}><FormInput label="المبلغ" value={amount} onChangeText={setAmount} keyboardType="numeric" placeholder="0" /></View><View style={styles.flex}><SelectField label="العملة" value={selectedCurrency ? `${selectedCurrency.displayName} (${currencyCode})` : currencyCode} placeholder="اختر العملة" onPress={() => setCurrencySheet(true)} /></View></View><DateField label="تاريخ الصرف" value={expenseDate} onChange={setExpenseDate} /><CashboxField value={cashboxId} onChange={setCashboxId} currencyCode={currencyCode} label="الصندوق الصادر منه المبلغ" /><FormInput label="ملاحظات" value={notes} onChangeText={setNotes} multiline placeholder="اختياري" /><View style={styles.actions}><PrimaryButton label="إلغاء" onPress={() => setOpen(false)} icon="close" variant="ghost" /><PrimaryButton label={create.isPending ? "جارٍ الحفظ..." : "حفظ"} onPress={() => { if (!category.trim() || !amount.trim() || Number(amount) <= 0 || !cashboxId) return Alert.alert("بيانات مطلوبة", "أدخل البند والمبلغ واختر الصندوق."); create.mutate({ category, costType, amount, cashboxId, currencyCode, expenseDate, notes: notes || undefined }); }} icon="save" disabled={create.isPending} /></View></View></View></Modal><SelectionSheet visible={typeSheet} title="اختر نوع التكلفة" items={costTypes.map((entry, index) => ({ id: index, label: entry.label, subtitle: "حساب التكاليف" }))} onClose={() => setTypeSheet(false)} onSelect={(item) => { setCostType(costTypes[item.id]?.value ?? "other"); setTypeSheet(false); }} /><SelectionSheet visible={currencySheet} title="اختر العملة" items={activeCurrencies.map((entry, index) => ({ id: index, label: entry.displayName, subtitle: entry.currencyCode }))} onClose={() => setCurrencySheet(false)} onSelect={(item) => { const selected = activeCurrencies[item.id]; if (selected) setCurrencyCode(selected.currencyCode as "YER" | "SAR" | "USD"); setCurrencySheet(false); }} />
  </LabScreen>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", alignItems: "flex-start", gap: 12 }, list: { gap: 9 }, card: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 16, padding: 13, flexDirection: "row-reverse", gap: 10, alignItems: "center" }, copy: { flex: 1, alignItems: "flex-end" }, name: { fontFamily: "Cairo-Bold", fontSize: 13 }, meta: { color: colors.muted, fontSize: 10, textAlign: "right", marginTop: 2 }, notes: { color: colors.muted, fontSize: 10, textAlign: "right", marginTop: 2 }, amountBlock: { alignItems: "flex-start", gap: 4 }, amount: { color: colors.danger, fontFamily: "Cairo-Bold", fontSize: 13 }, printText: { color: colors.primary, fontFamily: "Cairo-SemiBold", fontSize: 10 }, delete: { padding: 4 }, deleteText: { color: colors.danger, fontSize: 10, fontFamily: "Cairo-SemiBold" }, backdrop: { flex: 1, backgroundColor: "rgba(18,38,34,.42)", justifyContent: "center", padding: 20 }, modal: { backgroundColor: colors.background, borderRadius: 24, padding: 20, gap: 14 }, title: { fontFamily: "Cairo-Bold", fontSize: 18, textAlign: "right" }, twoCols: { flexDirection: "row-reverse", gap: 8 }, flex: { flex: 1 }, actions: { flexDirection: "row-reverse", gap: 10 }, pressed: { opacity: 0.7 } });
